server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devtube
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: aCJTSws5R_jQ5PCuAygd
            client-secret: RlGGf8SsJq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secretKey: asdasfasfagasdasdafaafasfaasdasfaggasfaasdahkghalksfjaklsjfaksfjlafklasjfkl
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh