server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devTube
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: asdasklfkalsfaskfjalsjflkalsafkasfasfasfasfasfsadasdadsadasfasfasasdasdafasdf
  expiration_time: 86400000 #1일